# Generated by Django 3.1.5 on 2021-02-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='warehouse_id',
            field=models.IntegerField(default=1),
        ),
    ]
