# Generated by Django 3.1.5 on 2021-01-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_id', models.IntegerField()),
                ('items_name', models.CharField(max_length=255)),
                ('quantity_available', models.IntegerField()),
                ('limit_price', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
                ('payment', models.CharField(choices=[('cash', 'cash'), ('credit', 'credit')], default='cash', max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_number', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
            ],
        ),
    ]
