# Generated by Django 3.1.5 on 2021-01-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210121_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='credential',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='order',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='products',
            name='tire',
        ),
        migrations.RemoveField(
            model_name='tires',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='tires',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='tires',
            name='vehicule',
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentMethods',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
        migrations.DeleteModel(
            name='Tires',
        ),
        migrations.DeleteModel(
            name='Vehicule',
        ),
    ]
