# Generated by Django 3.1.5 on 2021-01-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_date',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_at',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_on',
            field=models.DateField(auto_now=True),
        ),
    ]
