# Generated by Django 3.1.5 on 2021-01-22 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210121_2046'),
        ('orders', '0002_auto_20210122_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credentials',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ManyToManyField(to='products.Tires'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_interval',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='daily', max_length=50),
        ),
    ]
