# Generated by Django 3.1.5 on 2021-01-28 22:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210128_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='times',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='customers',
            name='start',
            field=models.DateField(default=datetime.datetime(2021, 1, 28, 22, 57, 17, 852630, tzinfo=utc)),
        ),
    ]
