# Generated by Django 3.1.5 on 2021-01-30 13:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210128_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.credentials'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='start',
            field=models.DateField(default=datetime.datetime(2021, 1, 30, 13, 38, 9, 923954, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.paymentmethods'),
        ),
    ]
