# Generated by Django 3.1.5 on 2021-02-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210130_2054'),
        ('orders', '0006_auto_20210130_2107'),
    ]

    operations = [
    ]
