# Generated by Django 3.1.5 on 2021-02-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210202_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='email',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
    ]
