# Generated by Django 3.1.5 on 2021-02-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210202_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='tel_number',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
    ]
