# Generated by Django 3.1.5 on 2021-02-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210202_1722'),
        ('orders', '0007_merge_20210201_0610'),
    ]

    operations = [
    ]
