# Generated by Django 3.1.5 on 2021-02-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210213_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payed', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.ManyToManyField(to='orders.Payment_status'),
        ),
    ]
