# Generated by Django 3.1.5 on 2021-02-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210215_1348'),
        ('orders', '0009_merge_20210202_1818'),
    ]

    operations = [
    ]
