# Generated by Django 3.1.5 on 2021-02-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210215_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='warehouse_id',
            field=models.IntegerField(default=1),
        ),
    ]
