# Generated by Django 3.1.5 on 2021-03-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orders_warehouse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='employee_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
