# Generated by Django 3.1.5 on 2021-02-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orders_warehouse_id'),
        ('orders', '0012_merge_20210215_2037'),
    ]

    operations = [
    ]
