# Generated by Django 3.1.5 on 2021-03-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_payment_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='payment_status',
            name='employee_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
