# Generated by Django 3.1.5 on 2021-03-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20210305_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_status',
            name='employee_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
