# Generated by Django 3.1.5 on 2021-03-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_merge_20210228_2041'),
        ('orders', '0015_auto_20210305_1547'),
    ]

    operations = [
    ]
