# Generated by Django 3.1.5 on 2021-03-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_productordered_custome_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_status',
            name='custome_payment',
            field=models.IntegerField(default=0),
        ),
    ]
