# Generated by Django 3.1.5 on 2021-01-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='add_at',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='add_on',
            field=models.DateField(auto_now=True),
        ),
    ]
