# Generated by Django 3.1.5 on 2021-01-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210121_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='tires',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
