# Generated by Django 3.1.5 on 2021-02-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tires_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tires',
            name='brands',
        ),
        migrations.AddField(
            model_name='tires',
            name='brands',
            field=models.CharField(default='Capronne,Mix', max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tires',
            name='profiles',
        ),
        migrations.AddField(
            model_name='tires',
            name='profiles',
            field=models.CharField(default='Doupro', max_length=255),
            preserve_default=False,
        ),
    ]
