# Generated by Django 3.1.5 on 2021-02-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210201_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tires',
            name='brands_str',
            field=models.CharField(default='Cramponne,Mix', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tires',
            name='profiles_str',
            field=models.CharField(default='Doupro', max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tires',
            name='brands',
        ),
        migrations.AddField(
            model_name='tires',
            name='brands',
            field=models.ManyToManyField(to='products.Brands'),
        ),
        migrations.RemoveField(
            model_name='tires',
            name='profiles',
        ),
        migrations.AddField(
            model_name='tires',
            name='profiles',
            field=models.ManyToManyField(to='products.Profiles'),
        ),
    ]
