# Generated by Django 3.1.5 on 2021-02-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210201_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='tires',
            name='warehouse_id',
            field=models.IntegerField(default=1),
        ),
    ]
