# Generated by Django 3.1.5 on 2021-02-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210226_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
