# Generated by Django 3.1.5 on 2021-02-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210227_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
