# Generated by Django 3.1.5 on 2021-03-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210227_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('receiver', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle', models.CharField(max_length=255)),
                ('profiles', models.CharField(max_length=255)),
                ('brands', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(max_length=100)),
                ('send_on', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
