# Generated by Django 3.1.5 on 2021-03-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_transfers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
