# Generated by Django 3.1.5 on 2021-03-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210320_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='size',
            field=models.CharField(default='1wd1', max_length=255),
            preserve_default=False,
        ),
    ]
