# Generated by Django 3.1.5 on 2021-03-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_transfers_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='sender_name',
            field=models.CharField(default='admin', max_length=255),
            preserve_default=False,
        ),
    ]
