# Generated by Django 3.1.5 on 2021-04-23 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_tires_pending_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.tires'),
        ),
    ]
