# Generated by Django 3.1.5 on 2021-04-24 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_products_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tires',
            name='tire_uid',
            field=models.CharField(default=uuid.UUID('81ea4cae-4dbd-4bab-8b84-94fd227d6405'), max_length=255),
        ),
    ]
