# Generated by Django 3.1.5 on 2021-04-24 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_tires_tire_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tires',
            name='tire_uid',
            field=models.CharField(default=uuid.UUID('4921a43d-a532-11eb-931f-64006a8e2a86'), max_length=255),
        ),
    ]
