# Generated by Django 3.1.5 on 2021-04-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_tires_tire_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tires',
            name='tire_uid',
        ),
    ]
