# Generated by Django 3.1.5 on 2021-04-24 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_tires_tire_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tires',
            name='tire_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
