# Generated by Django 3.1.5 on 2021-04-24 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_tires_tire_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tires',
            name='tire_uid',
            field=models.CharField(default=uuid.UUID('7d9cc9be-1427-432f-9894-bc07a005ed0e'), max_length=255),
        ),
    ]
