# Generated by Django 3.1.5 on 2021-04-26 08:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_tires_tire_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tires',
            name='tire_uid',
            field=models.CharField(default=uuid.UUID('5151c7f8-cfc0-43c4-8daf-4acd81999450'), max_length=255),
        ),
    ]
