# Generated by Django 3.1.5 on 2021-04-24 20:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_tires_tire_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tires',
            name='tire_uid',
            field=models.CharField(default=uuid.UUID('bbf2f1ea-00c8-41b9-a61f-7246a75ae0fd'), max_length=255),
        ),
    ]
