# Generated by Django 3.1.5 on 2021-04-25 01:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20210424_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tires',
            name='tire_uid',
            field=models.CharField(default=uuid.UUID('6cd7318b-5a79-4cdb-9358-c80d73a5108c'), max_length=255),
        ),
    ]
