# Generated by Django 3.1.5 on 2021-04-26 08:53

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20210426_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='tire_uid',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tires',
            name='tire_uid',
            field=models.CharField(default=uuid.UUID('50fdc92e-29e9-4ac3-89c5-18d938749b80'), max_length=255),
        ),
    ]
