# Generated by Django 3.1.5 on 2021-04-26 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20210426_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tires',
            name='tire_uid',
            field=models.CharField(default=uuid.UUID('caa23b38-a66e-11eb-91cf-64006a8e2a86'), max_length=255),
        ),
    ]
