# Generated by Django 3.1.5 on 2021-04-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20210426_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tires',
            name='tire_uid',
            field=models.CharField(max_length=255),
        ),
    ]
