# Generated by Django 3.1.5 on 2021-04-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20210425_0326'),
        ('products', '0030_auto_20210426_1110'),
    ]

    operations = [
    ]
