# Generated by Django 3.1.5 on 2021-04-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_merge_20210426_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tires',
            name='tire_uid',
            field=models.CharField(max_length=255),
        ),
    ]
