# Generated by Django 3.1.5 on 2021-04-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20210427_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='status',
            field=models.CharField(default='accepted', max_length=100),
        ),
    ]
