# Generated by Django 3.1.5 on 2021-04-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20210428_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(default='accepted', max_length=50),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
